name: covid_proj
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - numpy
  - pandas
  - matplotlib
  - seaborn
  - scikit-learn
  - torchvision
  - pytorch
  - torchaudio
  - streamlit
